config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "tours#index"
  get "up" => "rails/health#show", as: :rails_health_check
  get '/stats(/:id)', to: 'home#stats', as: :stats
  get 'terms_and_conditions', to: 'home#terms_and_conditions'
  get 'privacy_policy', to: 'home#privacy_policy'
  get 'disclaimer', to: 'home#disclaimer'
  get 'leaderboard', to: 'home#leaderboard'
  get 'credits', to: 'home#credits'
  get 'surprise_songs', to: 'home#surprise_songs'
  get 'guidelines', to: 'home#guidelines'


  devise_for :users, :controllers => {
    registrations: :registrations,
    sessions: :sessions
   }
  resources :tours do
    post 'copy', on: :member
  end
  resources :quizzes do
    post 'submit', on: :member
    post 'take', on: :member
    get 'take', on: :member
    get 'results', on: :member
    get 'progress', on: :member
    post 'open', on: :member
    post 'close', on: :member
    post 'live', on: :member
    post 'send_notification', on: :member
    post 'update_positions', on: :member
    post 'update_scores', on: :member
    resources :questions do
      get 'pick_surprise_song', on: :member
      post 'surprise_song_answer', on: :member
      get 'drawer_content', on: :member
      resources :choices
    end
  end
  resources :attempts do
    get 'share', on: :member
  end
  resources :choices do
    post 'correct', on: :member
    post 'incorrect', on: :member
  end
  resources :albums do
    resources :songs
  end

  resources :responses do
    resources :mashup_answers, only: :index
  end

  resources :mashup_answers  do
    patch 'switch_instrument', on: :member
    get 'add_guest', on: :member
  end

  resources :users do
    get 'unsubscribe', on: :member
    get 'subscribe', on: :member
  end

  resources :outfits do
    get 'tracker', on: :collection
  end

  resources :push_subscriptions, only: [:create]
  resources :push_notifications, only: [:create]
  resources :feedbacks do
    resources :feedback_responses
  end
  resources :setlists do
    resources :setlists_songs
  end

  resources :openers
  resources :notifications
  resources :leaderboards do
    get 'invite', on: :member
  end
end

app/models/leaderboard.rb
# == Schema Information
#
# Table name: leaderboards
#
#  id         :uuid             not null, primary key
#  name       :string           not null
#  slug       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  creator_id :uuid             not null
#
# Indexes
#
#  index_leaderboards_on_creator_id  (creator_id)
#
# Foreign Keys
#
#  fk_rails_...  (creator_id => users.id)
#
class Leaderboard < ApplicationRecord

  include Sluggable
  friendly_slug_scope to_slug: :name

  #associations
  belongs_to :creator, class_name: 'User'
  has_many :leaderboard_users, dependent: :destroy
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController

  before_action :set_tours, only: %i[index]
  before_action :find_leaderboard, except: %i[index]

  def index
    if params[:tour]
      @tour = Tour.friendly.find(params[:tour])
    else
      @tour = @tours.first
    end

    current_index = @tours.index(@tour)
    @next_tour = @tours[current_index - 1] if current_index && current_index > 0
    @previous_tour = @tours[current_index + 1] if current_index && current_index < @tours.size - 1

    if params[:tab] == 'general'
      general_leaderboard
    elsif params[:tab] == 'user'
      user_leaderboard
    end
  end

  def invite
    respond_to do |format|
      if current_user.id == @leaderboard.creator_id
        format.html { redirect_to leaderboards_path(tab: "user"), notice: "You can’t add yourself to your own leaderboard. Nice try." }
      elsif @leaderboard.leaderboard_users.exists?(user_id: current_user.id)
        format.html { redirect_to leaderboards_path(tab: "user"), notice: "You already belong to this leaderboard" }
      else
        @leaderboard.leaderboard_users.create!(user_id: current_user.id)
        current_user.leaderboard.leaderboard_users.create!(user_id: @leaderboard.creator_id )
        format.html { redirect_to leaderboards_path(tab: "user"), notice: "You are now leaderboard buddies with #{@leaderboard.creator.username}" }
      end
    end
  end

  private

  def set_tours
    @tours = Tour.where.not(status: [:pending, :cancelled]).where.not(base: true).where.not(preapp: true).order(number: :desc)
    @pagination = 50
  end

  def find_leaderboard
    @leaderboard = Leaderboard.friendly.find(params[:id])
  end

  def find_leaderboard
    @leaderboard = Leaderboard.friendly.find(params[:id])
  end

  def general_leaderboard
      @sorted_attempts = Leaderboards::General.call(tour_id: @tour.id)
      @paginated_attempts = @sorted_attempts.paginate(page: params[:page], per_page: @pagination)
  end

  def user_leaderboard
    @sorted_user_attempts = Leaderboards::User.call(tour_id: @tour.id, user_id: current_user.id)[:sorted_attempts]
    @users_without_attempts = Leaderboards::User.call(tour_id: @tour.id, user_id: current_user.id)[:users_without_attempts]
    @paginated_user_attempts = @sorted_user_attempts.paginate(page: params[:page], per_page: @pagination)
  end

end

app/views/leaderboards/_general_leaderboard.html.erb
<div class="flex justify-between items-center mt-10" >
  <%= render 'leaderboard_tour_navigator' %>
</div>


<% if params[:tab] == 'general' %>
  <% unless @paginated_attempts.blank? %>
    <div class="flex flex-col mt-16 lg:px-20 text-sm">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="dark:bg-black/10 bg-gray-50">
          <tr>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200 relative">
          <% @paginated_attempts.each_with_index do |a, index| %>
            <% attempt = Attempt.find(a['id']) %>
            <tr data-controller="confetti"  data-attempt-position = "<%= attempt.final_position %>" data-quiz-status="<%= attempt.quiz.tour.status %>" data-size="mini" id="targetRow">
              <canvas id="leaderboardConfetti" class="absolute h-[62px] w-3/4 lg:top-[30em] top-[28em]" data-confetti-target="canvas"></canvas>
              <td class="px-6 py-4 whitespace-nowrap text-sm">
                <span class="font-bold">
                <% if attempt.quiz.tour.status == 'closed' %>
                    <%= attempt.final_position %>
                <% else %>
                  <% page = params[:page].present? ? params[:page].to_i : 1 %>
                  <% position = ((page - 1) * @pagination) + (index + 1) %>
                  <%= position %>.
                <% end %>
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm lowercase flex items-center gap-3">
                <% path = params[:tab] == 'general' ? user_path(attempt.user) : attempt_path(attempt) %>

                <%= link_to path, class: "flex items-center gap-3 hover:underline w-full" do %>
                  <span class="<%= current_user.id == attempt.user.id ? 'font-semibold' : '' %>">@<%= attempt.user.username %></span>
                  <% if attempt.quiz.tour.closed? %>
                    <% if attempt&.final_position <= 3 %>
                      <%= image_tag attempt_badge(attempt.final_position), class: attempt_badge_class(attempt.final_position) %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm">
                <% if @tour.status == 'closed' %>
                   <span class="<%= current_user.id == attempt.user.id ? 'font-semibold' : '' %>"><%= attempt.final_score %></span>
                <% elsif @tour.status == 'live' %>
                  <span class="<%= current_user.id == attempt.user.id ? 'font-semibold' : '' %>"><%= attempt.score %></span>
                <% else %>
                  <i class="fa-solid fa-spinner text-gray-600" title="in progress"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="flex justify-end mt-3 overflow-x-scroll">
      <%= will_paginate @paginated_attempts %>
    </div>

  <% else %>
    <div class="flex justify-center items-center mt-20">
      No stats yet.
    </div>
  <% end %>
<% end %>

app/views/leaderboards/_invite.html.erb
<div class="lg:pt-10 pt-5 pb-20 px-5 min-h-screen flex flex-col gap-6">
  <i class="fa-solid fa-paper-plane text-5xl flex justify-center items-center"></i>

  <h5 class="text-lg font-semibold capitalize">Add friends to your leaderboard</h5>
  <p>On leaderboards you can see your friend's guesses by clicking on their name</p>

  <p class="mt-2">Send this link to your friends and they can add you.</p>

  <input id="inviteLink" value="<%= invite_leaderboard_url(current_user.leaderboard) %>" readonly class="border border-gray-300 rounded-md px-4 py-2 w-full focus:outline-none">

  <button id="copyButton" onclick="copyLink()" class="bg-black text-white px-4 py-2 rounded-md">Copy Link</button>
  </div>
</div>

<script>
  function copyLink() {
    var copyText = document.getElementById("inviteLink");
    copyText.select();
    copyText.setSelectionRange(0, 99999); // For mobile devices

    navigator.clipboard.writeText(copyText.value);

    // Show success message
    const copyButton = document.getElementById('copyButton')
    copyButton.innerText = 'Copied!'
  }
</script>

app/views/leaderboards/_leaderboard_tour_navigator.html.erb
<div class="flex md:justify-center items-center lg:gap-5 gap-2">
  <% if @previous_tour %>
    <%= link_to leaderboards_path(tour: @previous_tour, tab: params[:tab]), class: "font-semibold font-courier uppercase text-md border-2 border-black bg-black/95 dark:bg-gray-50 text-white dark:text-black py-2 rounded px-5" do %>
      <i class="fa-solid fa-circle-arrow-left"></i>
    <% end %>
  <% end %>

  <h5 class="font-semibold font-courier uppercase text-md border-2 border-black dark:border-gray-100 py-2 rounded lg:px-5 px-3"><%= @tour.title %></h5>

  <% if @next_tour %>
    <%= link_to leaderboards_path(tour: @next_tour, tab: params[:tab]), class: "font-semibold font-courier uppercase text-md border-2 border-black dark:border-gray-100 py-2 bg-black/95 dark:bg-gray-50 text-white dark:text-black rounded px-5" do %>
      <i class="fa-solid fa-circle-arrow-right"></i>
    <% end %>
  <% end %>
</div>

app/views/leaderboards/_user_leaderboard.html.erb
<div class="flex md:flex-row flex-col justify-between md:items-center mt-10 gap-6">
  <%= render 'leaderboard_tour_navigator' %>
  <%= render 'components/drawer', button_icon: 'fa-solid fa-plus', button_text: 'Add Friends', title: '', id: 'invite_friends', button_class: 'rounded py-2 px-4 dark:bg-black bg-gray-200 font-medium capitalize flex gap-2 items-center'  do %>
    <%= render 'invite' %>
   <% end %>
</div>

<% if params[:tab] == 'user' %>
  <div class="flex flex-col mt-16 lg:px-20 text-sm">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="dark:bg-black/10 bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">
          </th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">
          </th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">
          </th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 relative">
      <% unless @paginated_user_attempts.empty? %>
          <% @paginated_user_attempts.each_with_index do |a, index| %>
            <% attempt = Attempt.find(a['id']) %>
            <tr data-controller="confetti"  data-attempt-position = "<%= attempt.final_position %>" data-quiz-status="<%= attempt.quiz.tour.status %>" data-size="mini" id="targetRow">
              <canvas id="leaderboardConfetti" class="absolute h-[62px] lg:w-3/4 w-11/12 lg:top-[31em] top-[34em]" data-confetti-target="canvas"></canvas>
              <td class="px-6 py-4 whitespace-nowrap text-sm">
                <span class="font-bold">
                <% if attempt.quiz.tour.status == 'open' %>
                    <%= index + 1 %>
                <% elsif attempt.quiz.tour.status == 'closed' %>
                    <%= attempt.final_position %>
                <% else %>
                  <% page = params[:page].present? ? params[:page].to_i : 1 %>
                  <% position = ((page - 1) * @pagination) + (index + 1) %>
                  <%= position %>.
                <% end %>
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm lowercase flex items-center gap-3">
                <% path = params[:tab] == 'general' ? user_path(attempt.user) : attempt_path(attempt) %>

                <%= link_to path, class: "flex items-center gap-3 hover:underline w-full" do %>
                  <span class="<%= current_user.id == attempt.user.id ? 'font-semibold' : '' %>">@<%= attempt.user.username %></span>
                  <% if attempt.quiz.tour.closed? %>
                    <% if attempt.final_position <= 3 %>
                      <%= image_tag attempt_badge(attempt.final_position), class: attempt_badge_class(attempt.final_position) %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm">
              <% if @tour.status == 'closed' %>
                <span class="<%= current_user.id == attempt.user.id ? 'font-semibold' : '' %>"><%= attempt.final_score %></span>
              <% elsif @tour.status == 'live' %>
                  <span class="<%= current_user.id == attempt.user.id ? 'font-semibold' : '' %>"><%= attempt.score %></span>
                <% else %>
                  <i class="fa-solid fa-spinner text-gray-600" title="in progress"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>

        <% @users_without_attempts.each do |user| %>
            <tr class="text-gray-400">
              <td class="px-6 py-4 whitespace-nowrap text-sm">•</td>
              <td class="px-6 py-4 whitespace-nowrap text-sm lowercase <%= current_user.id == user.id ? 'font-semibold' : '' %>">
                  @<%= user.username %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm">•</td>
            </tr>
          <% end %>
      </tbody>
    </table>
  </div>

  <div class="flex justify-end mt-3 overflow-x-scroll">
    <%= will_paginate @paginated_user_attempts %>
  </div>
<% end %>

app/views/leaderboards/index.html.erb
<div class="lg:pt-32 pt-24 pb-20 lg:px-12 px-1 min-h-screen">

  <%= render 'components/breadcrumb', breadcrumbs: [
    { text: 'home', path: root_path },
    { text: "Leaderboards" },
  ]
  %>

    <% tabs = [
      { id: 'general', label: 'general', partial: 'general_leaderboard' },
      { id: "user", label: "#{current_user.leaderboard.name}", partial: 'user_leaderboard' },
    ] %>

  <div class="px-2 capitalize">
    <ul class="flex text-sm">
      <% tabs.each do |tab| %>
        <%= link_to leaderboards_path(tab: tab[:id], tour: params[:tour]), class: "p-4 cursor-pointer border-b #{ 'tab-active border-b-0' if params[:tab] == tab[:id] || (params[:tab].blank? && tab[:id] == 'general') }" do %>
          <%= tab[:label] %>
        <% end %>
      <% end %>
    </ul>

    <div class="p-4">
      <% tabs.each do |tab| %>
        <% if params[:tab] == tab[:id] || (params[:tab].blank? && tab[:id] == 'general') %>
          <%= render partial: tab[:partial] %>
        <% end %>
      <% end %>
    </div>
</div>


</div>