config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "tours#index"
  get "up" => "rails/health#show", as: :rails_health_check
  get '/stats(/:id)', to: 'home#stats', as: :stats
  get 'terms_and_conditions', to: 'home#terms_and_conditions'
  get 'privacy_policy', to: 'home#privacy_policy'
  get 'disclaimer', to: 'home#disclaimer'
  get 'leaderboard', to: 'home#leaderboard'
  get 'credits', to: 'home#credits'
  get 'surprise_songs', to: 'home#surprise_songs'
  get 'guidelines', to: 'home#guidelines'


  devise_for :users, :controllers => {
    registrations: :registrations,
    sessions: :sessions
   }
  resources :tours do
    post 'copy', on: :member
  end
  resources :quizzes do
    post 'submit', on: :member
    post 'take', on: :member
    get 'take', on: :member
    get 'results', on: :member
    get 'progress', on: :member
    post 'open', on: :member
    post 'close', on: :member
    post 'live', on: :member
    post 'send_notification', on: :member
    post 'update_positions', on: :member
    post 'update_scores', on: :member
    resources :questions do
      get 'pick_surprise_song', on: :member
      post 'surprise_song_answer', on: :member
      get 'drawer_content', on: :member
      resources :choices
    end
  end
  resources :attempts do
    get 'share', on: :member
  end
  resources :choices do
    post 'correct', on: :member
    post 'incorrect', on: :member
  end
  resources :albums do
    resources :songs
  end

  resources :responses do
    resources :mashup_answers, only: :index
  end

  resources :mashup_answers  do
    patch 'switch_instrument', on: :member
    get 'add_guest', on: :member
  end

  resources :users do
    get 'unsubscribe', on: :member
    get 'subscribe', on: :member
  end

  resources :outfits do
    get 'tracker', on: :collection
  end

  resources :push_subscriptions, only: [:create]
  resources :push_notifications, only: [:create]
  resources :feedbacks do
    resources :feedback_responses
  end
  resources :setlists do
    resources :setlists_songs
  end

  resources :openers
  resources :notifications
  resources :leaderboards do
    get 'invite', on: :member
  end
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :uuid             not null, primary key
#  email      :boolean          default(FALSE)
#  in_app     :boolean          default(FALSE)
#  link       :string
#  link_text  :string
#  message    :text
#  push       :boolean          default(FALSE)
#  status     :integer          default("unread")
#  subject    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :uuid
#
# Indexes
#
#  index_notifications_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Notification < ApplicationRecord
  has_paper_trail

  # associations
  belongs_to :user, optional: true

  # validations
  validates :subject, presence: true
  validates :message, presence: true

  # enums
  enum status: {
    unread: 0,
    read: 1
  }

  def self.status_options
    statuses.map { |k, _v| [k.humanize, k] }
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  before_action :authenticate_admin!, only: %i[new create edit update destroy]
  before_action :find_notification, except: %i[index new create]

  def index
    @notifications = current_user.notifications.where(in_app: true).order(created_at: :desc)
    @notifications.where(status: :unread).update(status: :read)
  end

  def new
    @notification = Notification.new
  end

  def show
    respond_to do |format|
      if @notification.update(status: 'read')
        if @notification.link
          format.html { redirect_to @notification.link}
        else
          format.html { redirect_to notifications_path }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        send_notification
        format.html { redirect_to notifications_path, notice: 'Notification was created successfully.'}
      else
        format.html { render :new, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to notifications_path, notice: 'Notification was created successfully.'}
      else
        format.html { render :new, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @notification.destroy!

    respond_to do |format|
      format.html { redirect_to notifications_path, notice: "Notification was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def find_notification
    @notification = Notification.find(params[:id])
  end

  def notification_params
    params.require(:notification).permit(:subject, :message, :email, :push, :in_app, :link, :link_test)
  end

  def send_notification
    NotificationWorker.perform_async(@notification.id)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, class: "contents") do |form| %>
  <% if notification.errors.any? %>
    <%= render 'shared/errors', object: notification %>
  <% end %>

  <div class="grid lg:grid-cols-2 gap-x-10 gap-y-5 lg:w-3/4 my-5">

    <div class="flex flex-col gap-1">
      <%= form.label :subject %>
      <%= form.text_field :subject, class: "border border-gray-200 outline-none px-3 py-2 bg-transparent w-full" %>
    </div>

    <div class="flex flex-col gap-1">
      <%= form.label :link %>
      <%= form.text_field :link, class: "border border-gray-200 outline-none px-3 py-2 bg-transparent w-full" %>
    </div>

    <div class="flex flex-col gap-1">
      <%= form.label :link_text %>
      <%= form.text_field :link_text, class: "border border-gray-200 outline-none px-3 py-2 bg-transparent w-full" %>
    </div>

    <div class="flex flex-col gap-1">
      <%= form.label :message %>
      <%= form.text_area :message, class: "border border-gray-200 outline-none px-3 py-2 bg-transparent w-full", required: true %>
    </div>

    <div class="flex items-center gap-2">
      <%= form.check_box :email, class: "h-8 w-8" %>
      <%= form.label :email %>
    </div>

    <div class="flex items-center gap-2">
      <%= form.check_box :push, class: "h-8 w-8" %>
      <%= form.label :push %>
    </div>

    <div class="flex items-center gap-2">
      <%= form.check_box :in_app, class: "h-8 w-8" %>
      <%= form.label :in_app %>
    </div>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded py-2 px-4 dark:bg-black bg-gray-200 font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<div class="lg:pt-32 pt-24 pb-20 px-12 min-h-screen">

  <%= render 'components/breadcrumb', breadcrumbs: [
    { text: 'home', path: root_path },
    { text: 'notifications', path: notifications_path },
    { text: "Edit Notification: #{@notification.subject}"}
  ] %>


  <h1 class="font-semibold text-xl font-courier capitalize">Edit Notification</h1>

  <%= render "form", notification: @notification %>

</div>

app/views/notifications/index.html.erb
<div class="lg:pt-32 pt-24 pb-20 min-h-screen">

  <div class="px-10">
    <%= render 'components/breadcrumb', breadcrumbs: [
      {text: 'home', path: root_path},
      {text: "Notifications"}
    ] %>
  </div>

  <div class="flex justify-end items-center px-10 mb-8 gap-4">
    <%= link_to new_notification_path, class: "rounded py-2 px-4 dark:bg-black bg-gray-200 shadow font-medium capitalize flex gap-2 items-center" do %>
      <i class="fa-solid fa-plus"></i>
      new notification
    <% end %>
  </div>

  <div class="flex flex-col gap-1">
   <% @notifications.each do |notification| %>
    <%= link_to notification_path(notification), class: "px-12 py-3 border dark:border-gray-900 flex flex-col gap-2 #{notification.unread? ? 'bg-gray-100 dark:bg-gray-900' : 'bg-gray-50 dark:bg-black'}" do %>
      <h5 class="font-medium text-sm capitalize flex md:flex-row flex-col gap-3 md:items-center">
        <%= notification.subject %>
        <span class='md:flex hidden'>:</span>
        <span class="text-sm capitalize font-normal"><%= notification.message %></span>
      </h5>
    <% end %>
   <% end %>
  </div>
</div>

app/views/notifications/new.html.erb
<div class="lg:pt-32 pt-24 pb-20 px-12 min-h-screen">

  <%= render 'components/breadcrumb', breadcrumbs: [
    { text: 'home', path: root_path },
    { text: 'notifications', path: notifications_path },
    { text: 'New Notification'}
  ] %>


  <h1 class="font-semibold text-xl font-courier capitalize">New Notification</h1>

  <%= render "form", notification: @notification %>

</div>