config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "tours#index"
  get "up" => "rails/health#show", as: :rails_health_check
  get '/stats(/:id)', to: 'home#stats', as: :stats
  get 'terms_and_conditions', to: 'home#terms_and_conditions'
  get 'privacy_policy', to: 'home#privacy_policy'
  get 'disclaimer', to: 'home#disclaimer'
  get 'leaderboard', to: 'home#leaderboard'
  get 'credits', to: 'home#credits'
  get 'surprise_songs', to: 'home#surprise_songs'
  get 'guidelines', to: 'home#guidelines'


  devise_for :users, :controllers => {
    registrations: :registrations,
    sessions: :sessions
   }
  resources :tours do
    post 'copy', on: :member
  end
  resources :quizzes do
    post 'submit', on: :member
    post 'take', on: :member
    get 'take', on: :member
    get 'results', on: :member
    get 'progress', on: :member
    post 'open', on: :member
    post 'close', on: :member
    post 'live', on: :member
    post 'send_notification', on: :member
    post 'update_positions', on: :member
    post 'update_scores', on: :member
    resources :questions do
      get 'pick_surprise_song', on: :member
      post 'surprise_song_answer', on: :member
      get 'drawer_content', on: :member
      resources :choices
    end
  end
  resources :attempts do
    get 'share', on: :member
  end
  resources :choices do
    post 'correct', on: :member
    post 'incorrect', on: :member
  end
  resources :albums do
    resources :songs
  end

  resources :responses do
    resources :mashup_answers, only: :index
  end

  resources :mashup_answers  do
    patch 'switch_instrument', on: :member
    get 'add_guest', on: :member
  end

  resources :users do
    get 'unsubscribe', on: :member
    get 'subscribe', on: :member
  end

  resources :outfits do
    get 'tracker', on: :collection
  end

  resources :push_subscriptions, only: [:create]
  resources :push_notifications, only: [:create]
  resources :feedbacks do
    resources :feedback_responses
  end
  resources :setlists do
    resources :setlists_songs
  end

  resources :openers
  resources :notifications
  resources :leaderboards do
    get 'invite', on: :member
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ terms_and_conditions privacy_policy disclaimer]

  def stats
    @chart_type = params[:chart_type] || 'bar_chart'
    @user = current_user.admin? ? User.friendly.find(params[:id]) : current_user
    @attempts = @user.attempts
    @current_streak = @user.current_streak
    @max_streak = @user.max_streak
    attempts_count = @user.attempts.size

    @attempts_stats = @attempts.includes(:responses, quiz: :tour).map { |attempt| [attempt.quiz.tour.title.titleize, attempt.score]}

    attempts_for_average = @attempts.includes([:quiz, :responses]).reject { |attempt| attempt.quiz.tour.status == 'open' }

    @average_score = attempts_for_average.size.zero? ? 0 : attempts_for_average.map(&:score).sum.to_i / attempts_for_average.size
    @lifetime_points = attempts_for_average.map(&:score).sum
    @best_score = attempts_for_average.map(&:score).max || 0

    @responses = @attempts.includes([:quiz, :responses]).reject { |attempt| attempt.quiz.tour.status == 'open' }.map(&:responses).flatten.uniq

    correct_responses = @responses.select { |response| response&.choice&.correct }
    questions = correct_responses.map(&:question).flatten.sort_by { |question| question.era }
    all_question_accuracy = questions.group_by { |qn| qn.content }.transform_values(&:count)
    total_responses = @user.attempts.map(&:responses).size
    @all_questions = Question.joins(quiz: :tour)
                             .where.not(tours: { preapp: true })
                             .where.not(include_album_and_song: true)
                             .order(:era)
                             .order(:position)
                             .pluck(:content, :position)
                             .to_h


    @questions_predictions_data = @all_questions.map do |question_content, position|
      correct_count = all_question_accuracy[question_content] || 0
      percentage = ((correct_count.to_f / total_responses.to_f) * 100).round(2)
      [question_content, "#{percentage}%"]
    end

    custom_era_order = Question.eras.keys

    @questions_predictions_by_era_data = Question.joins(quiz: :tour)
                                                 .where.not(tours: { preapp: true })
                                                 .where.not(include_album_and_song: true)
                                                 .group_by(&:era).sort_by { |era, _| custom_era_order.index(era) }
                                                 .map do |era, era_questions|
      era_questions_accuracy = era_questions.map(&:content).map do |content|
        all_question_accuracy[content] || 0
      end.first

      total_era_questions = era_questions.group_by(&:content).length * total_responses

      era_accuracy_percentage = ((era_questions_accuracy.to_f / total_era_questions.to_f) * 100).round(2)

      [era.humanize.titleize, "#{era_accuracy_percentage}%"]
    end.to_h
  end

  def surprise_songs
    tours = Tour.where.not(base: true)
                .where(status: [:closed, :live])
                .order(number: :desc)
    if params[:query]
      @tours = tours.search(params[:query])
    else
      @tours = tours
    end
    @view = params[:view] || 'card_view'
    @albums = Album.includes(:songs).where(status: :active)
    @correct_mashups = MashupAnswer.includes([question: [quiz: :tour]]).where(correct: true)
    records
    @album_song_stats = @correct_mashups.group_by { |mashup| mashup.album_id }.map do |album_id, mashups|
      album = Album.find(album_id)
      album_title = album.abbr.titleize
      count = mashups.size
      [album_title, count, album.created_at]
    end.sort_by { |_, _, created_at| created_at }
  end

  private

  def records
    @correct_mashups = MashupAnswer.includes(question: [quiz: :tour]).where(correct: true)

    # Process song counts
    @song_counts = @correct_mashups.group(:song_id).count
    @most_frequent_song_id, @most_frequent_song_count = @song_counts.max_by { |_song_id, count| count }
    @most_frequent_song = Song.find(@most_frequent_song_id)

    @song_performance_counts = @correct_mashups
      .where(song_id: @most_frequent_song_id)
      .group(:instrument)
      .count

    # Process album counts
    @album_counts = @correct_mashups.group(:album_id).count
    @most_frequent_album_id, @most_frequent_album_count = @album_counts.max_by { |_album_id, count| count }
    @most_frequent_album = Album.find(@most_frequent_album_id)

    @album_performance_counts = @correct_mashups
      .where(album_id: @most_frequent_album_id)
      .group(:instrument)
      .count

    # Find tours with specific conditions
    @tours_for_instruments = {}
    @correct_mashups.each do |mashup|
      next unless mashup.correct

      tour_title = mashup.question.quiz.tour.title
      instrument = mashup.instrument

      if @tours_for_instruments[instrument].nil?
        @tours_for_instruments[instrument] = { count: 0, tours: [] }
      end

      @tours_for_instruments[instrument][:count] += 1
      @tours_for_instruments[instrument][:tours] << tour_title if @tours_for_instruments[instrument][:count] <= 3
    end
  end


end

app/views/home/_album_song_distribution.html.erb
<div class="flex flex-col gap-2 mt-5">
  <% @albums.each_with_index do |album, index| %>

    <% album_guitar = @correct_mashups.where(album_id: album.id).where(instrument: :guitar) %>
    <% album_piano = @correct_mashups.where(album_id: album.id).where(instrument: :piano) %>

    <div class="accordion" data-controller="accordion">
      <div class="accordion-item">
        <h2 class="accordion-header mb-0">
          <button class="accordion-button relative flex items-center w-full py-2 px-5 <%= album_bg_color(album.abbr) %> text-xs uppercase font-medium text-left rounded-none transition" type="button" data-action="click->accordion#toggle" data-accordion-target="header">
          <div class="flex gap-3">
            <span><%= album.title %></span>
            •
            <span> TOTAL (<%= album_guitar.size + album_piano.size %>)</span>
            •
            <span> GUITAR (<%= album_guitar.size %>)</span>
            •
            <span> PIANO (<%= album_piano.size %>)</span>
          </div>
            <i class="fa fa-chevron-down ml-auto" data-accordion-target="icon"></i>
          </button>
        </h2>
        <div class="accordion-collapse <%= index == 0 ? '' : 'collapsed' %>" data-accordion-target="content">
          <div class="accordion-body py-4 px-2 overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200 overflow-x-auto">
              <thead class="dark:bg-black/10 bg-gray-50 border">
                <tr>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider border sticky left-0 bg-gray-50 dark:bg-black">
                    Song
                  </th>

                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider border">
                    total
                  </th>

                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider border ">
                    <div class="flex items-center gap-1">
                      <%= image_tag 'icons/guitar.png', class: 'w-4' %>
                      <span>guitar</span>
                    </div>
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider border">
                    <div class="flex items-center gap-1">
                      <%= image_tag 'icons/piano.png', class: 'w-4' %>
                      <span>piano</span>
                    </div>
                  </th>


                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 text-xs border">
                <% album.songs.each_with_index do |song, s_index| %>
                  <% guitar = @correct_mashups.where(song_id: song.id).where(instrument: :guitar) %>
                  <% piano = @correct_mashups.where(song_id: song.id).where(instrument: :piano) %>


                  <tr class="<%= is_in_setlist?(song) ? album_bg_color(album.abbr) : '' %>">
                    <td class="px-6 py-4 break-words border sticky left-0 lg:w-60 w-5 <%= is_in_setlist?(song) ? album_bg_color(album.abbr) : 'bg-gray-50 dark:bg-black' %>">
                      <p class="flex  gap-3">
                        <%= song.title %>
                        <% if is_in_setlist?(song) %>
                        <span class="text-8px">[setlist]</span>
                        <% end %>
                      </p>
                    </td>

                    <td class="break-words lg:w-60 w-5 border">
                      <div class="py-2 px-6">
                        <%= piano.size + guitar.size %>
                      </div>
                    </td>

                    <td class="break-words lg:w-60 w-5 border">
                      <div class="py-2 <%= guitar.size.positive? ? 'border-b' : '' %> px-6">
                        <%= guitar.size %>
                      </div>

                      <% if guitar.size.positive? %>
                        <div class=" py-2 px-6 ">
                          <%= guitar.map { |mashup| mashup.question.quiz.tour.title }.join(', ') %>
                        </div>
                      <% end %>
                    </td>

                    <td class="break-words lg:w-60 w-5 border">
                      <div class="py-2 <%= piano.size.positive? ? 'border-b' : '' %> px-6">
                        <%= piano.size %>
                      </div>

                      <% if piano.size.positive? %>
                        <div class=" py-2 px-6 ">
                          <%= piano.map { |mashup| mashup.question.quiz.tour.title }.join(', ') %>
                        </div>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_album_song_graph.html.erb
<div class="flex flex-col capitalize overflow-x-scroll">
  <div class="mt-10">
    <%= render_chart @album_song_stats, 'Album', 'No data', 'albums', chart_type: 'column_chart', height: '600px'   %>
  </div>
</div>

app/views/home/_card_view.html.erb
<div class="grid lg:grid-cols-3 lg:gap-5 gap-16 rounded text-xs">
  <% @tours.order(number: :desc).each do |tour| %>
    <div class="border rounded border-gray-300 dark:border-gray-600 bg-gray-100 dark:bg-black/30">
      <h5 class="uppercase font-semibold text-center uppercase border-b border-gray-300 dark:border-gray-600  py-2"> <%= tour.title %> </h5>
      <div class="pt-2 flex flex-col gap-2">
        <% tour.mashup_answers.order(:created_at).where(correct: true).includes(:album, :song).group_by(&:instrument).each do |instrument, mashup_answers| %>
          <div class="py-1 text-xs flex justify-center items-center gap-2">
            <% if instrument == 'guitar' %>
              <%= image_tag 'icons/guitar.png', class: 'w-4' %>
            <% else %>
              <%= image_tag 'icons/piano.png', class: 'w-4' %>
            <% end %>
            <h6 class="font-medium uppercase"><%= instrument %></h6>
          </div>
          <% mashup_answers.each do |mashup_answer| %>
            <div class="<%= album_bg_color(mashup_answer.album.abbr) %> px-2 py-1 capitalize font-normal flex justify-between items-center ">
                <span><%= mashup_answer.album.abbr %> - <%= mashup_answer.song.title %> </span>
              <span class="flex flex-row items-center gap-2 relative">
                <% if mashup_answer.guest.present? %>
                <button onclick="document.getElementById('tooltip-<%= mashup_answer.id %>').classList.toggle('hidden')">
                  <i class="fa-solid fa-user text-xs"></i>
                </button>
                <span id="tooltip-<%= mashup_answer.id %>" class="hidden bg-slate-950 dark:bg-gray-50 text-white dark:text-black px-2 py-1 rounded text-white absolute right-10 bottom-6 text-xs w-40 z-50"> Special Guest: <%= mashup_answer.guest %>
                </span>
                <% end %>

                <% if current_user.admin? %>
                  <%= render 'components/dropdown', title: '', icon_class: 'fa-solid fa-ellipsis', items: mashup_dropdown_items(mashup_answer) %>
                <% end %>
              </span>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_guide.html.erb
<div class="flex flex-col mt-5 gap-5">
    <h5 class="text-sm font-bold uppercase">
      Guide
      <hr class="mb-2" />
    </h5>

  <div class="flex flex-col gap-4">
      <% @albums.each do |album| %>
        <div class="flex gap-2 text-xs font-medium">
          <div class="h-5 w-5 <%= album_bg_color(album.abbr) %>"> </div> - <%= album.title %>
        </div>
      <% end %>
  </div>
</div>

app/views/home/_highest_records.html.erb
<div class="flex lg:flex-row flex-col lg:gap-10 gap-5 mt-5">
  <div class="flex flex-col gap-2 text-xs">
    <h4 class="text-sm font-bold uppercase">Most Frequent Song</h4>
    <div class="<%= album_bg_color(@most_frequent_song.album.abbr) %> p-4 rounded shadow-md flex flex-col gap-3">
      <h5 class="text-sm font-bold"><%= @most_frequent_song.title %></h5>
      <p class="font-medium">Total: <%= @most_frequent_song_count %></p>
      <% @song_performance_counts.each do |instrument, count| %>
        <p class="flex flex-col gap-1 font-normal">
          <span><%= instrument.capitalize %>: <%= count %></span>
        </p>
      <% end %>
    </div>
  </div>

  <div class="flex flex-col gap-2 text-xs">
    <h4 class="text-sm font-bold uppercase">Most Frequent Album</h4>
    <div class="<%= album_bg_color(@most_frequent_album.abbr) %> p-4 rounded shadow-md flex flex-col gap-3">
      <h5 class="text-sm font-bold"><%= @most_frequent_album.title %></h5>
      <p class="font-medium">Total: <%= @most_frequent_album_count %></p>
      <% @album_performance_counts.each do |instrument, count| %>
        <p class="flex flex-col gap-1 font-normal">
          <span><%= instrument.capitalize %>: <%= count %></span>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_question_show_table.html.erb
<% tours = Tour.where.not(base: true).where.not(status: [:pending, :cancelled]).where.not(preapp: true).order(number: :desc)%>
<div class="flex flex-col mt-10 overflow-x-scroll">
  <table class="min-w-full divide-y divide-gray-200 relative">
    <thead class="dark:bg-black/10 bg-gray-50">
      <tr>
        <th scope="col" class="px-6 py-3 text-left lg:text-sm text-xs font-medium uppercase tracking-wider sticky left-0 bg-gray-50" >
          Question
        </th>
        <% tours.each do |tour| %>
          <th scope="col" class="p-2 text-left lg:text-sm text-xs font-medium uppercase tracking-wider">
            <%= tour.title %>
          </th>
        <% end %>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
      <% @all_questions.each do |question_content, _position| %>
        <tr>
          <td class="px-6 py-4 lg:text-sm text-xs sticky left-0 bg-gray-50 w-40 break-words" >
            <%= question_content  %>
          </td>
          <% tours.each do |tour| %>

            <% quiz = tour&.quiz %>
            <% response = @responses.select { |response| response.question.content == question_content && response.question.quiz.tour_id == tour.id }.first %>


            <td class="p-2 lg:text-sm text-xs">
              <% if response %>
                <% correct_response_exists = response.question.choices.find_by(correct: true).present? %>
                <% if response.choice.correct %>
                  <i class="fa-solid fa-check text-green-500"></i>
                <% else %>
                  <% if tour.status == 'live' %>
                    <% if correct_response_exists %>
                      <i class="fa-solid fa-xmark text-red-500"></i>
                    <% else %>
                      <i class="fa-solid fa-spinner"></i>
                    <% end %>
                  <% else %>
                    <i class="fa-solid fa-xmark text-red-500"></i>
                  <% end %>
                <% end %>
              <% else %>
                <% if tour.status == 'live' || tour.status == 'open' %>
                  <i class="fa-solid fa-spinner"></i>
                <% else %>
                  --
                <% end %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/home/_songs.html.erb
<div class="flex justify-end gap-2 items-center">
  <%= form_with url: surprise_songs_path, method: :get, local: true, data: { controller: 'view-switcher' } do %>
    <div class="mb-4 flex justify-end">
      <div class="flex items-center space-x-2">
        <select id="view-switch" name="view" data-view-switcher-target="select" class="w-32 pl-3 pr-10 py-2 text-xs bg-gray-50 dark:bg-black sm:text-sm rounded">
          <option value="card_view" <%= 'selected' if params[:view] == 'card_view' %>>Card View</option>
          <option value="table_view" <%= 'selected' if params[:view] == 'table_view' %>>Table View</option>
        </select>
      </div>
    </div>
  <% end %>

  <% if params[:view] == 'table_view' %>
    <%= form_with url: surprise_songs_path, method: :get, local: true, data: { controller: 'view-switcher' } do %>
      <div class="mb-4 flex justify-end">
        <div class="flex items-center space-x-2 capitalize">
          <input type="hidden" name="view" value="table_view">
          <select id="view-switch" name="table_view" data-view-switcher-target="select" class="w-32 pl-3 pr-10 py-2 text-xs bg-gray-50 dark:bg-black sm:text-sm rounded">
            <option value="by_instrument" <%= 'selected' if params[:table_view] == 'by_instrument' %>>By Instrument</option>
            <option value="by_tour" <%= 'selected' if params[:table_view] == 'by_tour' %>>By  Tour</option>
          </select>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= form_with url: surprise_songs_path, method: :get, local: true, class: 'flex gap-2 items-center mb-10' do |form| %>
  <%= form.text_field :query, placeholder: "Search by show...",
                      class: "w-full px-3 py-2 border rounded text-xs bg-gray-50 dark:bg-black/50" %>
  <button type='submit' class="py-2 px-2 flex items-center gap-2 capitalize bg-black  dark:bg-gray-50 dark:text-black text-white rounded">
    <i class="fa-solid fa-magnifying-glass"></i>
  </button>

  <%= link_to surprise_songs_path(tab: 'songs'), class:"py-2 px-2 flex items-center gap-2 capitalize bg-black  dark:bg-gray-50 dark:text-black text-white rounded" do %>
    <i class="fa-solid fa-rotate-right"></i>
  <% end %>
<% end %>

<%= render partial: params[:view] || 'card_view' %>

app/views/home/_songs_stats.html.erb
<div class="flex flex-col mt-5 gap-10">
  <div class="flex  flex-col  gap-10">
    <h5 class="text-sm font-bold uppercase">
      Album Distribution by Instrument
      <hr class="mb-2" />
    </h5>
    <%= render 'instrument_distribution' %>
  </div>

  <div class="flex flex-col gap-5">
    <h5 class="text-sm font-bold uppercase">
      Album / Song Records
      <hr class="mb-2" />
    </h5>
    <%= render 'highest_records' %>
  </div>

  <div class="flex flex-col">
    <h5 class="text-sm font-bold uppercase flex justify-between">
      <span>Album / Song Graph</span>
    </h5>
    <hr class="mb-2" />
    <%= render 'album_song_graph' %>
  </div>

  <div class="flex flex-col gap-5">
    <h5 class="text-sm font-bold uppercase">
      Album / Song Distribution Breakdown
      <hr class="mb-2" />
    </h5>
    <%= render 'album_song_distribution' %>
  </div>
</div>

app/views/home/_table_view.html.erb
<%= render partial: params[:table_view] || 'by_instrument' %>

app/views/home/credits.html.erb
<div class="lg:pt-32 pt-24 pb-20 px-12 min-h-screen">

  <%= render 'components/breadcrumb', breadcrumbs: [
    { text: 'home', path: root_path },
    { text: 'credits'}
  ] %>

  <hr />


  <div class="flex flex-col justify-center p-3  gap-4 lg:w-3/4 text-sm">
    <h5 class="font-courier uppercase">Credits</h5>
    <ul class="list-disc flex flex-col gap-4">
     <li>
      Swiftball concept - <a href="https://x.com/swiftballers" target="_blank" class="font-medium hover:underline">@swiftballers</a>.
     </li>
     <li>
      Outfit tracker system - <a href="https://x.com/nicksversion" target="_blank" class="font-medium hover:underline">@nicksversion</a>.
     </li>
     <li>
      Stats Archive - <a href="https://x.com/carolnicolet" target="_blank" class="font-medium hover:underline">@carolnicolet</a>.
     </li>
    </ul>
  </div>

</div>

app/views/home/guidelines.html.erb
<div class="lg:pt-32 pt-24 pb-20 px-12 min-h-screen">

  <%= render 'components/breadcrumb', breadcrumbs: [
    { text: 'home', path: root_path },
    { text: 'guidelines'}
  ] %>

  <hr />

  <div data-controller="accordion" class="space-y-4">

    <div class="border-b border-gray-200">
      <button
        type="button"
        class="flex justify-between items-center w-full py-4 text-left focus:outline-none"
        data-action="click->accordion#toggle"
      >
        <span class="text-base font-medium capitalize">How it works</span>
        <i class="fas fa-chevron-down" data-accordion-target="icon"></i>
      </button>
      <div class="collapse" data-accordion-target="content">
        <div class="py-4 lg:w-3/4">
          <p class="text-gray-800 leading-7 text-sm mt-5">
            The questions follow the setlist chronologically. Make your predictions on outfits and surprise songs, with each prediction being worth a certain amount of points. Each correct answer earns you points, and the person with the highest point value wins!
          </p>
          <p class="text-gray-800 leading-7 text-sm mt-5">
            In the event of a tie, the player who submitted their guesses earliest wins.
          </p>
          <p class="text-gray-800 leading-7 text-sm mt-5">
            The quizz closes before the start of the show (specifically, when the clock comes on the screen)
          </p>
          <p class="text-gray-800 leading-7 text-sm mt-5">
             There are <b class='bold'>NO PRIZES</b> to be won (see <%= link_to 'disclaimer', disclaimer_path, class: 'underline font-medium' %>) but you get really cool confetti on the leaderboard and a trophy emoji & more confetti on your guesses page.
          </p>
        </div>
      </div>
    </div>

    <div class="border-b border-gray-200">
      <button
        type="button"
        class="flex justify-between items-center w-full py-4 text-left focus:outline-none"
        data-action="click->accordion#toggle"
      >
        <span class="text-base font-medium capitalize">Surprise Song Points</span>
        <i class="fas fa-chevron-down" data-accordion-target="icon"></i>
      </button>
      <div class="collapse" data-accordion-target="content">
        <div class="py-4 lg:w-3/4">
          <p class="text-gray-800 leading-7 text-sm mt-5">
            Surpise song points are based on how you answer the mashup question and points split on the album and song.
          </p>
          <p class="text-gray-800 leading-7 text-sm mt-5">
            Example, if your prediction was a mashup of two songs and you picked two songs each song can earn a maximum of 3 points.
          </p>
          <p class="text-gray-800 leading-7 text-sm mt-5">
            The 3 points will be split into 1.5 for correct album and 1.5 for correct song for the right instrument.
          </p>
          <p class="text-gray-800 leading-7 text-sm mt-5">
            If only the album is correct but on the wrong instrument you get 1 point.
          </p>
          <p class="text-gray-800 leading-7 text-sm mt-5">
            Correct song wrong instrument will still get you full points based on your mashup prediction.
          </p>
        </div>
      </div>
    </div>

    <div class="border-b border-gray-200">
      <button
        type="button"
        class="flex justify-between items-center w-full py-4 text-left focus:outline-none"
        data-action="click->accordion#toggle"
      >
        <span class="text-base font-medium capitalize">What counts as unhinged</span>
        <i class="fas fa-chevron-down" data-accordion-target="icon"></i>
      </button>
      <div class="collapse" data-accordion-target="content">
        <div class="py-4 lg:w-3/4">
          <p class="text-gray-800 leading-7 text-sm mt-5">
            Something unhinged is considered to be something *planned* by Taylor or her team that is unexpected by the audience and deviates from the regular course of the show. For example: Speak Now TV announcement, Karma MV premiere, vault scramble, etc. Please note that as We am not Taylor and We am not privy to her plans, it is hard to exactly define this and list examples that could fully encompass the scope of unhingedness.
          </p>
          <p class="text-gray-800 leading-7 text-sm mt-5">
            For setlist changes and additions, we operate on a 3 show rule where 1 show is a surprise, 2 shows is a coincidence, and 3 shows is a pattern. After the 3rd show where a setlist item is modified and stays modified, the change is no longer considered unhinged. In short, 1-3 shows are considered unhinged, but the 4th show after a change is no longer unhinged. (For example, Long Live added after SNTV, No Body No Crime with HAIM, and the TTPD setlist.)
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/leaderboard.html.erb
<div class="lg:pt-32 pt-24 pb-20 lg:px-12 px-5 min-h-screen">

  <%= render 'components/breadcrumb', breadcrumbs: [
    { text: 'home', path: root_path },
    { text: "Leaderboards" },
  ]
  %>

   <div data-controller='tabs'>
    <%= render 'components/tabs', tabs: [
      { id: 'general', label: 'general', partial: 'general_leaderboard' },
      { id: "#{current_user.username}", label: "#{current_user.username}'s Version", partial: 'user_leaderboard' },
    ] %>
  </div>

</div>

app/views/home/surprise_songs.html.erb
<div class="lg:pt-32 pt-24 pb-20 lg:px-12 px-6 min-h-screen">
  <%= render 'components/breadcrumb', breadcrumbs: [
    { text: 'home', path: root_path },
    { text: 'surprise songs'}
  ] %>

  <div data-controller='tabs'>
    <%= render 'components/tabs', tabs: [
      { id: 'songs', label: 'songs', partial: 'songs' },
      { id: 'stats', label: 'stats', partial: 'songs_stats' },
      { id: 'guide', label: 'guide', partial: 'guide' }
    ] %>
  </div>
</div>