config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "tours#index"
  get "up" => "rails/health#show", as: :rails_health_check
  get '/stats(/:id)', to: 'home#stats', as: :stats
  get 'terms_and_conditions', to: 'home#terms_and_conditions'
  get 'privacy_policy', to: 'home#privacy_policy'
  get 'disclaimer', to: 'home#disclaimer'
  get 'leaderboard', to: 'home#leaderboard'
  get 'credits', to: 'home#credits'
  get 'surprise_songs', to: 'home#surprise_songs'
  get 'guidelines', to: 'home#guidelines'


  devise_for :users, :controllers => {
    registrations: :registrations,
    sessions: :sessions
   }
  resources :tours do
    post 'copy', on: :member
  end
  resources :quizzes do
    post 'submit', on: :member
    post 'take', on: :member
    get 'take', on: :member
    get 'results', on: :member
    get 'progress', on: :member
    post 'open', on: :member
    post 'close', on: :member
    post 'live', on: :member
    post 'send_notification', on: :member
    post 'update_positions', on: :member
    post 'update_scores', on: :member
    resources :questions do
      get 'pick_surprise_song', on: :member
      post 'surprise_song_answer', on: :member
      get 'drawer_content', on: :member
      resources :choices
    end
  end
  resources :attempts do
    get 'share', on: :member
  end
  resources :choices do
    post 'correct', on: :member
    post 'incorrect', on: :member
  end
  resources :albums do
    resources :songs
  end

  resources :responses do
    resources :mashup_answers, only: :index
  end

  resources :mashup_answers  do
    patch 'switch_instrument', on: :member
    get 'add_guest', on: :member
  end

  resources :users do
    get 'unsubscribe', on: :member
    get 'subscribe', on: :member
  end

  resources :outfits do
    get 'tracker', on: :collection
  end

  resources :push_subscriptions, only: [:create]
  resources :push_notifications, only: [:create]
  resources :feedbacks do
    resources :feedback_responses
  end
  resources :setlists do
    resources :setlists_songs
  end

  resources :openers
  resources :notifications
  resources :leaderboards do
    get 'invite', on: :member
  end
end

app/models/attempt.rb
# == Schema Information
#
# Table name: attempts
#
#  id             :uuid             not null, primary key
#  final_position :integer
#  final_score    :integer
#  slug           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  quiz_id        :uuid             not null
#  user_id        :uuid             not null
#
# Indexes
#
#  index_attempts_on_quiz_id  (quiz_id)
#  index_attempts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (quiz_id => quizzes.id)
#  fk_rails_...  (user_id => users.id)
#
class Attempt < ApplicationRecord
  has_paper_trail

  include MashupScores
  include Sluggable
  friendly_slug_scope to_slug: :title

  # associations
  belongs_to :user
  belongs_to :quiz
  has_many :responses, dependent: :destroy
  has_many :questions, through: :responses, dependent: :destroy
  has_many :mashup_answers, through: :responses, dependent: :destroy

  # validations
  validate :single_attempt_per_quiz, on: :create

  # instance methods

  def title
    "#{user.username} #{quiz.title}"
  end

  def total_questions
    questions.size
  end

  def correct_attempt_questions
    correct_questions_count = responses.select { |response| response.predicted_correctly?}.size
  end

  def questions_with_correct_answers
    correct_questions_count = questions.select { |question| question.choices.where(correct: true).exists? }.size
  end

  def score
    score = 0

    responses.includes([:choice, :question]).each do |response|
      if response.choice&.correct
        score += response.question.points
      end
    end

    if quiz.correct_mashups.present?
      (score + piano_mashup_score + guitar_mashup_score + mixup_mashup_score).to_i
    else
      score.to_i
    end
  end

  def total_possible_points
    quiz&.questions.sum(:points)
  end

  def position
    attempt_scores = quiz.attempts.order(:created_at).map(&:score).compact.sort.reverse
    attempt_scores.index(score)&.+(1)
  end

  private

  def single_attempt_per_quiz
    if Attempt.exists?(user_id: user_id, quiz_id: quiz_id)
      errors.add(:base, "You can only attempt this quiz once")
    end
  end
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  include OrderQuestions

  before_action :authenticate_not_admin!, only: %i[index]
  before_action :set_attempt, except: %i[index]
  before_action :set_quiz, only: %i[show edit update share]
  before_action :order_questions, only: %i[edit]
  before_action :check_tour_open, only: %i[edit]

  def index
    @attempts = current_user.attempts
                            .includes(quiz: :tour)
                            .joins(quiz: :tour)
                            .order('tours.start_time DESC')
                            .paginate(page: params[:page], per_page: 10)

    @attempts_stats = current_user.attempts.includes(:responses, quiz: :tour).map { |attempt| [attempt.quiz.tour.title.titleize, attempt.score]}

  end

  def show
    responses = @attempt.responses.includes(:question, :mashup_answers, choice: [ :image_attachment, question: :choices ])
    if @quiz.tour.era_order == 'new_order'
      @questions_by_era = responses.joins(:question)
                                   .order('questions.position ASC')
                                   .group_by { |response| response.question.era }
    else
      order_clause = "CASE questions.era #{Arel.sql(Question.old_era_order)} END"
      @questions_by_era = responses
                            .joins(:question)
                            .order(Arel.sql(order_clause))
                            .order('questions.position ASC')
                            .group_by { |response| response.question.era }
    end
  end

  def share
    if @quiz.tour.status != 'open'
      @responses = @attempt.responses.includes(:question, :mashup_answers, choice: [ :question,:image_attachment ])
    else
      @responses = @attempt.responses.includes(:question, :mashup_answers, choice: [ :image_attachment ])
    end
  end

  def update
    if @quiz.tour.status == 'open'
      responses = params[:attempt][:responses]

      responses.each do |question_id, choice_id|
        response = @attempt.responses.find_by(question_id: question_id)

        if response.update(choice_id: choice_id)
          next
        else
          redirect_to attempt_path(@attempt), alert: "Something went wrong. Please try again."
          return
        end
      end

      redirect_to attempt_path(@attempt), notice: "Your answers have been updated!"
    elsif @quiz.tour.status == 'closed' || @quiz.tour.status == 'live'
      redirect_to attempt_path(@attempt), alert: "Sorry this quiz has been closed!"
    end
  end

  def download_pdf
    pdf = AttemptPdf.new(attempt: @attempt)
    send_data pdf.render,
              filename: "#{@attempt.slug}.pdf",
              type: 'application/pdf',
              disposition: 'inline'
  end

  private

  def set_attempt
    if current_user.username != params[:id].split('-').first
      @attempt = Attempt.includes([:responses]).friendly.find(params[:id])
    else
      @attempt = current_user.attempts.friendly.find(params[:id])
    end
  end

  def set_quiz
    @quiz = @attempt.quiz
  end

  def check_tour_open
    respond_to do |format|
      if @attempt.quiz.tour.status == 'closed' || @attempt.quiz.tour.status == 'live'
        format.html { redirect_to attempt_path(@attempt), alert: "Quiz is closed & can't be edited" }
      elsif  @attempt.quiz.tour.status == 'pending'
        format.html { redirect_to root_path, alert: 'Hey early bird, Quiz is not yet open' }
      else
       format.html  { render :edit }
      end
    end
  end
end

app/helpers/attempts_helper.rb
module AttemptsHelper
  def attempt_dropdown_items(quiz)
    attempt = current_user.attempts.find_by(quiz_id: quiz.id)

    if attempt
      items = []

      if quiz.tour.status == 'open'
        items << { path: attempt_path(attempt), icon_class: 'fa-solid fa-wand-magic-sparkles', menu_text: 'View Predictions' }

        items << { path: edit_attempt_path(attempt), icon_class: 'fa-solid fa-pencil', menu_text: 'Edit Predictions' }
      end
    end

    items
  end

  def attempt_badge(position)
    case position
    when 1
      'trophy.png'
    when 2
      'badge2.png'
    when 3
      'badge3.png'
    end
  end

  def attempt_badge_class(position)
    case position
    when 1
      'w-8  -ml-2'
    when 2
      'w-6 -ml-1'
    when 3
      'w-6 -ml-1'
    end
  end
end

app/views/attempts/edit.html.erb
<div class="lg:pt-32 pt-24 pb-20 min-h-screen">

  <div class="px-5 py-3">
    <%= render 'components/breadcrumb', breadcrumbs: [
      { text: 'home', path: root_path },
      { text: "Edit #{@attempt.quiz.title} predictions"}
    ] %>
    </div>


  <h5 class="font-semibold font-courier uppercase text-md px-5">
    <%= @quiz.title %>
    <% if @quiz.tour.status == 'open' %>
      <span> (closes <%= time_user_timezone(@quiz.tour&.quiz_live_time, current_user) %>)
      </span>
    <% end %>
  </h5>

  <%= form_with(model: @attempt, url: attempt_path(@attempt), method: :patch, local: true) do |f| %>
    <% @questions_by_era.each do |era, questions| %>
      <div class="mt-10 capitalize">
        <h1 class="<%= era_color(era) %> font-bold uppercase text-lg p-2 flex justify-center items-center"><%= era.humanize %></h1>
        <% questions.each_with_index do |question, q_index| %>
          <div class="flex flex-col px-5 py-3 ">
            <p class="flex lg:flex-row flex-col gap-2 justify-between lg:text-base text-sm">
              <%= (q_index + 1).to_s.rjust(2, '0') %>. <%= question.content %> (worth <%= question.points %> points)
              <%= render 'questions/history_drawer', question: question %>
            </p>
            <div class="grid <%= question&.choices&.first&.image&.attached? ? 'lg:grid-cols-6 grid-cols-2' : 'grid-cols-1' %> gap-4">
              <% question.choices.includes([image_attachment: :blob]).order(:position).each_with_index do |choice, c_index| %>
                <div class="choice py-3 flex flex-col gap-4 relative">
                 <% if choice.image.attached? %>
                  <%= image_tag(choice.image, alt: choice.content, class: 'w-full h-72 object-cover object-center rounded')%>
                  <% if choice.new_item == false && choice.label != 'no_label' %>
                    <button type="button" class="label-tag absolute px-4 py-1 rounded text-xs -top-0 -right-1 rotate-360 <%= label_color (choice.label)%>" onclick="document.getElementById('tooltip-<%= choice.id %>').classList.toggle('hidden')" >
                      <span class="font-medium"><%= choice.label.humanize %></span>
                    </button>

                    <span id="tooltip-<%= choice.id %>" class="bg-slate-950 dark:bg-gray-50 text-white dark:text-black px-2 py-1 rounded text-white absolute text-xs right-1 top-7 hidden">
                      <%= label_title(choice.label) %>
                    </span>
                  <% end %>
                 <% end %>
                  <div class="flex gap-2 items-center capitalize font-medium">
                  <%= f.fields_for :responses do |response_form| %>
                    <%= response_form.radio_button "#{question.id}", choice.id, required: true, checked: @attempt.responses.find_by(question_id: question.id)&.choice_id == choice.id %>
                    <%= choice.content %>
                  <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <% if question.include_album_and_song %>
            <% mashup_answers = @attempt.responses.includes(:mashup_answers).where(question_id: question.id).flat_map(&:mashup_answers) %>
            <% mashup_answers.each do |mashup| %>
              <div class="flex justify-between px-5 py-3">
                <p class="flex gap-2 items-center font-medium capitalize">
                  <%= mashup.album.abbr %> - <%= mashup.song.title %>
                </p>
                <%= link_to edit_mashup_answer_path(mashup) do %>
                  <i class="fa-solid fa-pencil px-4"></i>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <div class="mt-10 flex justify-center">
      <%= f.submit "Update Responses", class: "dark:bg-black bg-gray-200 font-bold py-2 px-4 rounded w-3/4 mb-4 hover:dark:bg-gray-900 hover:bg-gray-100 cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/attempts/index.html.erb
<div class="lg:pt-32 pt-24 pb-20 lg:px-12 px-5 min-h-screen">

  <%= render 'components/breadcrumb', breadcrumbs: [
    { text: 'home', path: root_path },
    { text: "attempts" },
  ]
  %>

  <div class="flex justify-between items-center">
    <h5 class="font-semibold font-courier uppercase text-md ">attempts (<%= @attempts.size %>) </h5>
  </div>

  <div class="flex flex-col mt-10">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="dark:bg-black/10 bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">
            position
          </th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">
            Quiz
          </th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">
            score
          </th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <% @attempts.includes([:responses]).each_with_index do |attempt, index| %>
          <% quiz = attempt.quiz %>
          <% tour = quiz.tour %>
        <tr class="<%= tour.status == 'cancelled' ? 'text-red-500': '' %>">
          <td class="px-6 py-4 whitespace-nowrap text-sm">
            <% if tour.status == 'closed' %>
              <%= attempt.final_position %> / <%= quiz.total_attempts %>
            <% elsif tour.status == 'cancelled' %>
            <% elsif tour.status == 'open' %>
            <% else %>
              <%= index + 1 %>
            <% end %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm capitalize hover:underline flex items-center gap-2">
            <%= link_to quiz.title, attempt_path(attempt)  %>
            <% if tour.status == 'closed' %>
              <% if (attempt.final_position <= 3) %>
                <%= image_tag attempt_badge(attempt.final_position), class: attempt_badge_class(attempt.final_position), title: "#{attempt.final_position}" %>
              <% end %>
            <% end %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm">
            <% if @tour.status == 'closed' %>
              <%= attempt.final_score %>
            <% elsif @tour.status == 'live' %>
              <%= attempt.score %>
             <% elsif tour.status == 'cancelled' %>
               <i class="fa-solid fa-xmark text-red-500" title="cancelled"></i>
             <% else %>
              <i class="fa-solid fa-spinner text-gray-600" title="pending"></i>
             <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <div>

  <div class="flex justify-end mt-3 overflow-x-scroll">
    <%= will_paginate @attempts %>
  </div>

  <% unless @attempts.empty? %>
    <div class="flex flex-col lg:mt-20 mt-5 capitalize overflow-x-scroll">
        <div class="flex lg:flex-row flex-col justify-between">
          <h5 class="uppercase font-bold flex items-center gap-3">
            <i class="fa-solid fa-chart-pie"></i>
              attempts stats
          </h5>
          <div class="mt-4 mb-2 flex lg:flex-row flex-col lg:items-center lg:text-base text-sm">
            <%= form_tag(attempts_path , method: 'get', class: 'flex lg:flex-row flex-col lg:items-center gap-2', id: 'attemptsChartForm') do %>
              <%= select_tag 'chart_type', options_for_select(chart_types.map { |chart| [chart.humanize, chart] }, @chart_type), class: 'w-40 h-10 capitalize lg:text-base text-sm dark:bg-black bg-gray-50', id: 'attemptsChartTypeSelect'  %>
            <% end %>
          </div>
        </div>
        <hr class="my-1" />
        <div class="mt-10">
          <%= render_chart @attempts_stats, 'Attempts', 'No data', 'attempts', chart_type: 'column_chart', height: '600px'   %>
        </div>
    </div>
  <% end %>

</div>

<script>
  document.getElementById('attemptsChartTypeSelect').addEventListener('change', function() {
    document.getElementById('attemptsChartForm').submit();
  });
</script>

app/views/attempts/show.html.erb
<% breadcrumbs = [
    { text: 'home', path: root_path }
  ]
%>

<% tour = @attempt.quiz.tour %>

<% if current_user.admin? %>
   <% breadcrumbs.insert(1, { text: "#{@attempt.quiz.title}", path: tour_path(@attempt.quiz.tour)}) %>
   <% breadcrumbs << { text: "#{@attempt.user.username} predictions"} %>
<% else %>
   <% { text: "#{@attempt.quiz.title} predictions"} %>
<% end %>


<div class="lg:pt-44 pt-24 pb-20 min-h-screen relative" data-controller="confetti" data-attempt-position="<%= @attempt.final_position %>" data-quiz-status="<%= @quiz.tour.status %>" data-size="full">
  <div class="p-5">
    <%= render 'components/breadcrumb', breadcrumbs: breadcrumbs %>
  </div>

  <div class="flex lg:flex-row flex-col gap-5 justify-between lg:items-center p-5">
    <h5 class="font-semibold font-courier uppercase text-md lg:mt-0 <%= @quiz.tour.status == 'live' || @quiz.tour.status == 'closed' ? 'mt-24' : 'mt-0' %>">
      <% if current_user != @attempt.user %>
        @<%= @attempt.user.username %>'s
      <% else %>
        your
      <% end %>
      <%= @quiz.title %> predicitions
      <% if @quiz.tour.status == 'open' %>
      <span> (closes <%= time_user_timezone(@quiz.tour&.quiz_live_time, current_user) %>)
      </span>
    <% end %>
    </h5>

    <% if current_user.id == @attempt.user.id %>
     <div class="flex items-center gap-4">
        <%= link_to share_attempt_path(@attempt), class:'flex items-center gap-2 text-sm px-4 py-2 bg-slate-100 dark:bg-white/10 capitalize rounded' do %>
          <i class="fa-solid fa-share"></i>
          <span>share</span>
        <% end %>
        <% if @quiz.tour == 'open' %>
          <%= link_to edit_attempt_path(@attempt), class:'flex items-center gap-2 text-sm px-4 py-2 bg-slate-100 dark:bg-white/10 capitalize rounded' do %>
            <i class="fa-solid fa-pencil"></i>
            <span>edit</span>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>


    <% if  tour.status == 'closed' %>
      <div class="absolute right-10 lg:top-24 top-20 font-handwriting">

          <% if (@attempt.final_position <= 3) %>
            <div class="absolute -top-2 z-10 -left-5">
              <%= image_tag attempt_badge(@attempt.final_position), class: 'w-16' %>
            </div>
          <% else %>
            <div class="bg-red-500 h-5 w-5 rounded-full absolute top-4 z-10 left-1"></div>
          <% end %>

          <div class="-rotate-3 bg-yellow-300 dark:bg-rose-300 shadow-lg p-5 w-44 h-36 m-4 rounded-lg flex flex-col gap-2 dark:text-black">
              <h2 class="text-xl underline tracking-wide font-bold mb-2 uppercase">results</h2>
              <span class="text-lg">POINTS: <%= @attempt.final_score %> / <%= @attempt.total_possible_points %> </span>
              <span class="text-lg"">POSITION: <%= @attempt.final_position %> / <%= @quiz.total_attempts %> </span>
          </div>
      </div>
    <% end %>

    <% if  tour.status == 'live' %>
      <div class="absolute right-10 lg:top-24 top-20 font-handwriting">
          <div class="bg-green-500 h-5 w-5 rounded-full absolute top-4 z-10 left-1 animate-ping"></div>
          <div class="sticky-note dark:bg-black bg-white p-5 w-44 h-44 m-4 rounded-lg flex flex-col gap-2">
              <h2 class="text-xl underline tracking-wide font-bold mb-2 uppercase">live progress</h2>
              <span class="text-lg">QNS: <%= @attempt.correct_attempt_questions %> / <%= @attempt.questions_with_correct_answers %> </span>
              <span class="text-lg">POINTS: <%= @attempt.score %> / <%= @attempt.total_possible_points %> </span>
              <span class="text-lg"">POSITION: <%= @attempt.position %> / <%= @attempt.quiz.total_attempts %> </span>
          </div>
      </div>
    <% end %>


    <% @questions_by_era.each do |era, responses| %>
      <h1 class="<%= era_color(era) %> font-bold uppercase text-lg p-2 flex justify-center items-center"><%= era.humanize %></h1>
      <div class="grid lg:grid-cols-3">
        <% responses.group_by { |response| response.question.id }.each_with_index do |(question_id, grouped_responses), index| %>
          <% response = grouped_responses.first %>
          <% choice = response&.choice %>
          <div class="flex flex-col lg:justify-start justify-center px-5 py-3 gap-2 capitalize">
            <div class="flex flex-col gap-3">
              <%= (index + 1).to_s.rjust(2, '0') %>. <%= response.question.content %> (worth <%= response.question.points %> points)
              <%= image_tag(choice&.image, alt: "#{choice&.content}", class: 'w-full lg:h-[30rem] object-cover object-center rounded', loading: 'lazy') if choice&.image&.attached? %>
              <p class="font-medium capitalize flex items-center lg:gap-4 gap-2">
                <% if choice&.correct %>
                  <i class="fa-solid fa-circle-check text-green-600"></i>
                <% end %>
                <%= choice&.content %>
                <% if choice&.correct %>
                  <span class="bg-green-600 text-white p-2 rounded text-xs flex items-center gap-2">
                   + <%= choice.question.points %>
                  </span>
                <% end %>
              </p>
            </div>

            <% correct_choice = response.question.choices.find_by(correct: true) %>
            <% if !choice&.correct && correct_choice.present? %>
              <p class="text-red-600 text-sm flex gap-3 items-center font-semibold capitalize">
                <i class="fa-solid fa-xmark"></i>
                <span> correct choice: <%= correct_choice.content %> </span>
              </p>
            <% end %>

            <% mashup_answers = grouped_responses.
            flat_map(&:mashup_answers) %>
            <% correct_mashups = response.question.mashup_answers.includes([:album, :song]).where(response_id: nil, correct: true) %>
            <% correct_albums = correct_mashups.pluck(:album_id) %>
            <% correct_songs = correct_mashups.pluck(:song_id) %>

            <% question_content = 'pick piano acoustic set album and song' %>
            <% piano_question = @attempt.quiz&.questions.find_by(content: question_content) %>
            <% piano_correct_mashups = piano_question.mashup_answers.where(response_id: nil, correct: true) %>
            <% piano_correct_albums = piano_correct_mashups.pluck(:album_id) %>
            <% piano_correct_songs = piano_correct_mashups.pluck(:song_id) %>
            <% piano_mashup_qn =  response.question.piano_mashup ? response.question : nil  %>
            <% if piano_mashup_qn %>
              <% piano_mashup_ans = response.choice.content %>
              <% @piano_points = mashup_max_score(piano_mashup_ans) %>
            <% end %>

            <% question_content = 'pick guitar acoustic set album and song' %>
            <% guitar_question = @attempt.quiz&.questions.find_by(content: question_content) %>
            <% guitar_correct_mashups = guitar_question.mashup_answers.where(response_id: nil, correct: true) %>
            <% guitar_correct_albums = guitar_correct_mashups.pluck(:album_id) %>
            <% guitar_correct_songs = guitar_correct_mashups.pluck(:song_id) %>
            <% guitar_mashup_qn =  response.question.guitar_mashup ? response.question : nil  %>
            <% if guitar_mashup_qn %>
              <% guitar_mashup_ans = response.choice.content %>
              <% @guitar_points = mashup_max_score(guitar_mashup_ans) %>
            <% end %>


            <% if mashup_answers.present? %>
              <div class="grid lg:grid-cols-1 gap-5">
                <div class="flex flex-col gap-3">
                  <% mashup_answers.each do |mashup| %>
                    <div class="flex items-center gap-4">
                      <p class="font-medium capitalize flex items-center gap-2">
                          <% if correct_albums.present? %>
                            <% if correct_albums.include?(mashup.album_id) %>
                              <i class="fa-solid fa-circle-check text-green-600"></i>
                            <% elsif (response.question.id != piano_question.id) &&piano_correct_albums.include?(mashup.album_id) %>
                              <i class="fa-solid fa-keyboard text-green-600"></i>
                            <% elsif (response.question.id != guitar_question.id) &&guitar_correct_albums.include?(mashup.album_id) %>
                              <i class="fa-solid fa-guitar text-green-600"></i>
                            <% else %>
                              <i class="fa-solid fa-xmark text-red-600"></i>
                            <% end %>
                          <% end %>
                        <%= mashup.album.abbr %>
                        - <%= mashup.song.title %>
                        <% if correct_songs.present? %>
                          <% if correct_songs.include?(mashup.song_id) %>
                            <i class="fa-solid fa-circle-check text-green-600"></i>
                          <% elsif (response.question.id != piano_question.id) &&piano_correct_songs.include?(mashup.song_id) %>
                            <i class="fa-solid fa-keyboard text-green-600"></i>
                          <% elsif (response.question.id != guitar_question.id) &&guitar_correct_songs.include?(mashup.song_id) %>
                              <i class="fa-solid fa-guitar text-green-600"></i>
                          <% else %>
                            <i class="fa-solid fa-xmark text-red-600"></i>
                          <% end %>
                        <% end %>
                      </p>

                      <!-- mashup points -->
                      <% if correct_albums.include?(mashup.album_id) && correct_songs.include?(mashup.song_id) %>
                        <span class="bg-green-600 text-white p-2 rounded text-xs flex items-center gap-2">
                         <% if response.question.id == guitar_question.id %>
                            + <%= format_score (@guitar_points * 2) %>
                         <% elsif response.question.id == piano_question.id %>
                            + <%= format_score (@piano_points * 2) %>
                         <% end %>
                        </span>
                      <% elsif (response.question.id != piano_question.id) &&piano_correct_albums.include?(mashup.album_id) && piano_correct_songs.include?(mashup.song_id)  %>
                        <span class="bg-green-600 text-white p-2 rounded text-xs flex items-center gap-2">
                          + <%= format_score (@guitar_points * 2) %>
                        </span>
                      <% elsif (response.question.id != guitar_question.id) &&guitar_correct_albums.include?(mashup.album_id) && guitar_correct_songs.include?(mashup.song_id)  %>
                        <span class="bg-green-600 text-white p-2 rounded text-xs flex items-center gap-2">
                          + <%= format_score (@piano_points * 2) %>
                        </span>
                      <% elsif correct_albums.include?(mashup.album_id) %>
                        <span class="bg-green-600 text-white p-2 rounded text-xs flex items-center gap-2">
                         <% if response.question.id == guitar_question.id %>
                            + <%= format_score (@guitar_points) %>
                         <% elsif response.question.id == piano_question.id %>
                            + <%= format_score (@piano_points) %>
                         <% end %>
                        </span>
                      <% elsif correct_songs.include?(mashup.song_id) %>
                        <span class="bg-green-600 text-white p-2 rounded text-xs flex items-center gap-2">
                         <% if response.question.id == guitar_question.id %>
                            + <%= format_score (@guitar_points) %>
                         <% elsif response.question.id == piano_question.id %>
                            + <%= format_score (@piano_points) %>
                         <% end %>
                        </span>
                      <% elsif (response.question.id != piano_question.id) &&piano_correct_albums.include?(mashup.album_id)  %>
                        <span class="bg-green-600 text-white p-2 rounded text-xs flex items-center gap-2">
                         + 1
                        </span>
                      <% elsif (response.question.id != guitar_question.id) &&guitar_correct_albums.include?(mashup.album_id)  %>
                        <span class="bg-green-600 text-white p-2 rounded text-xs flex items-center gap-2">
                         + 1
                        </span>
                      <% end %>
                    </div>

                  <% end %>
                </div>

                <% if correct_mashups.present?  %>
                  <p class="font-medium underline text-orange-500 capitalize"> correct surprise songs </p>

                  <div class="flex flex-col gap-3">
                    <% correct_mashups.each do |mashup| %>
                      <span class="dark:text-violet-200 text-violet-500 capitalize text-sm font-medium"> <%= mashup.album.abbr %> - <%= mashup.song.title %> </span>
                    <% end %>
                  </div>
                <% end %>

              </div>
            <% end %>

          </div>
        <% end %>
      </div>
    <% end %>
</div>